language: csharp

env:
  global:
  - environment=Development
  - APP_NAME=rainbow-api
  - AWS_ECR_ACCOUNT=860436917626
  - AWS_ACCESS_KEY_ID=AKIAJG4PXAIR5DQTNS2Q
  - AWS_SECRET_ACCESS_KEY=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

mono: none
dotnet: 3.1
# solution: RainbowApp.sln

# script:
#   - dotnet restore
#   - dotnet build
install:
- dotnet restore

script:
- dotnet build ./RainbowApp.Api/RainbowApp.Api.csproj --configuration Release

after_success:
- eval $(aws ecr get-login --no-include-email --region ap-northeast-2)
- docker build -t rainbow-api --build-arg ASPNETCORE_ENVIRONMENT=$environment --build-arg AWS_DEFAULT_REGION=AP-NORTHEAST-2 --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY .
#- docker tag $APP_NAME:$TRAVIS_BUILD_ID $AWS_ECR_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID
- docker tag rainbowappapi:latest $AWS_ECR_ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com/$APP_NAME:$environment
#- docker push $AWS_ECR_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID
- docker push $AWS_ECR_ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com/$APP_NAME:$environment