sudo: required #is required to use docker service in travis
language: python

env:
  - environment=Development APP_NAME=rainbow-api

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
install:
  - pip3 install --upgrade pip
  - sudo apt-get install awscli

before_script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region ap-northeast-2

script: echo "Deploying to AWS ECR releases ..."

after_success:
  - eval $(aws ecr get-login --no-include-email --region ap-northeast-2)
  - docker build -t rainbow-api .
  - docker images
  - docker tag $APP_NAME:latest $AWS_ECR_ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com/$APP_NAME:$environment
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com/$APP_NAME:$environment

notifications:
  slack:
    rooms:
      - travis encrypt "ubcareslack:EffFB5OqnmtfKWPiQJeBZ3sv#cell_rainbow_cicd" --add notifications.slack