# https://woomin.netlify.app/Posts/2020-05-12-CodeDeploy/
version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/

hooks:
  BeforeInstall:
      - location: scripts/beforeInstall.bash
        runas: root
  AfterInstall:
      - location: scripts/afterInstall.bash
        runas: root